### ISSUE TITLE
Does this useragent support the lookup api of its predecesssor

### ISSUE THREAD

**Issue by mathurs** [hyperwatch/useragent#21]
The approach is definitely interesting, just wanted to check if there is a plan to support the lookup function so we don't have to worry about caching in a high throughput environment.

Thanks

**Comment by znarf** [comment]
I actually removed `lookup` because it felt better to me to let users build it themselves if they need it. Also allowing to remove dependency on the `lru-cache` package.

**Comment by mathurs** [comment]
Sure, understand the choice.
